[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "ejs"]
  included_files = ["views/**"]
  node_bundler = "esbuild"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true